In [1]:
import numpy as np

# Numpy:
  -  NumPy can be used to perform a wide variety of mathematical operations on arrays. It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.

In [3]:
# Creating numpy arrays
          #- type casting a list 
         # - arange()
          ##- np.random.randint

In [4]:
arr=np.array(1,2,3,4,5)

TypeError: array() takes from 1 to 2 positional arguments but 5 were given

In [5]:
arr=np.array([1,2,3,4,5])

In [6]:
arr

array([1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [11]:
arr.size

5

In [13]:
arr.shape

(5,)

In [16]:
arr.max()

5

In [17]:
arr.min()

1

# 2D Array

In [22]:
arr2=np.arange(20).reshape(5,4)

In [23]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [28]:
arrd=np.arange(25).reshape(5,5)

In [29]:
arrd

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
arr2d=np.random.randint(1,25,(5,5))

In [31]:
arr2d

array([[24,  1, 12, 23,  1],
       [ 5,  4, 20,  1, 17],
       [ 8, 16,  1, 23,  6],
       [18, 10, 23,  9, 17],
       [19, 23, 20, 11, 12]])

In [32]:
arr2d=np.random.randint(1,20,(5,4))

In [33]:
arr2d

array([[15, 11, 12, 17],
       [ 8, 19,  7,  7],
       [ 9, 14,  9,  8],
       [10, 13, 13, 10],
       [18, 12,  1, 14]])

In [34]:
arr2d=np.random.randint(1,20,(5,5))

In [35]:
arr2d

array([[ 7,  5, 15, 13, 16],
       [ 2,  3,  4,  1,  9],
       [ 2,  5, 15,  5, 10],
       [11, 12,  5, 11, 18],
       [14, 18,  5, 15,  1]])

In [36]:
arr2d=np.random.randint(1,25,(6,6))

# Array Slicing and Indexing

In [37]:
arr2d

array([[16, 18, 13, 13, 10, 21],
       [ 2, 18, 10, 10, 20, 14],
       [10, 13,  3, 16, 10, 10],
       [24, 11, 18, 18,  2, 13],
       [ 7,  7, 10,  1,  5, 10],
       [23, 10, 19, 14, 18, 16]])

In [43]:
# for finding  13
arr2d[3,3]


18

In [44]:
# for 16
arr2d[-1,-1] , arr2d[5,5] ,arr2d[5][5]

(16, 16, 16)

In [48]:
arr2d[3:5,1:3]

array([[11, 18],
       [ 7, 10]])

In [49]:
arr2d[4: ,4:]

array([[ 5, 10],
       [18, 16]])

In [51]:
arr2d[:,5] # this is indexing not slicing

array([21, 14, 10, 13, 10, 16])

# 3D Array

In [52]:
arr3d=np.arange(20).reshape(2,2,5)

In [53]:
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [56]:
arr3d=np.arange(40).reshape(2,4,5) # depth row and columns 

In [57]:
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])

In [58]:
arr3d=np.random.randint(1,40,(2,5,4))

In [59]:
arr3d

array([[[13,  9,  3, 11],
        [ 4, 35, 12,  9],
        [37, 18,  6, 14],
        [21, 23,  6, 21],
        [35,  4, 30,  7]],

       [[24, 30, 36,  5],
        [20, 38, 29, 24],
        [35,  6, 39,  5],
        [20, 22,  7, 31],
        [13, 34, 17,  9]]])

# Vectorize oprations 
 - vectorize opration is opration in which the opration is apply in all arrry or funcation

In [60]:
arr

array([1, 2, 3, 4, 5])

In [61]:
arr*2

array([ 2,  4,  6,  8, 10])

In [62]:
arr+2

array([3, 4, 5, 6, 7])

In [63]:
arr/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [64]:
arr**2

array([ 1,  4,  9, 16, 25])

In [65]:
arr%100

array([1, 2, 3, 4, 5], dtype=int32)

In [67]:
arr**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [68]:
# All mathematical opration is apply on the array array perfome very past opration within second

In [72]:
zero=np.zeros(6)

In [73]:
zero

array([0., 0., 0., 0., 0., 0.])

In [75]:
zero=np.zeros((5,4),dtype=int)

In [76]:
zero

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [77]:
ones=np.ones(8)

In [78]:
ones

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [79]:
ones=np.ones((5,4),dtype=int)

In [80]:
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [81]:
emppty=np.empty(7)

In [82]:
emppty

array([0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
       0.0000000e+000, 0.0000000e+000, 3.1408287e-317])

In [84]:
full=np.full(5,4)

In [85]:
full

array([4, 4, 4, 4, 4])

In [87]:
full=np.full((5,4),10)

In [88]:
full

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [89]:
print(full.dtype)

int32


In [93]:
full=full.astype('float')# changing the data types of array

In [94]:
full.dtype

dtype('float64')

In [95]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [96]:
arr2d

array([[16, 18, 13, 13, 10, 21],
       [ 2, 18, 10, 10, 20, 14],
       [10, 13,  3, 16, 10, 10],
       [24, 11, 18, 18,  2, 13],
       [ 7,  7, 10,  1,  5, 10],
       [23, 10, 19, 14, 18, 16]])

In [98]:
arrd

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [111]:
arr2d=np.arange(36).reshape(6,6)

In [112]:
arr2=np.random.randint(1,36,(6,6))

In [113]:
arr2

array([[12, 30, 16, 28, 33, 15],
       [14,  2, 28, 17, 33, 30],
       [17, 24,  4,  1, 11, 32],
       [35, 30, 24,  5, 18,  6],
       [ 7, 25,  4, 20, 20, 26],
       [25, 21,  7,  6, 28,  1]])

In [114]:
arr2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [115]:
arr2+arr2d

array([[12, 31, 18, 31, 37, 20],
       [20,  9, 36, 26, 43, 41],
       [29, 37, 18, 16, 27, 49],
       [53, 49, 44, 26, 40, 29],
       [31, 50, 30, 47, 48, 55],
       [55, 52, 39, 39, 62, 36]])

In [116]:
arr2*arr2d

array([[  0,  30,  32,  84, 132,  75],
       [ 84,  14, 224, 153, 330, 330],
       [204, 312,  56,  15, 176, 544],
       [630, 570, 480, 105, 396, 138],
       [168, 625, 104, 540, 560, 754],
       [750, 651, 224, 198, 952,  35]])

In [118]:
arr2d/arr2

array([[0.00000000e+00, 3.33333333e-02, 1.25000000e-01, 1.07142857e-01,
        1.21212121e-01, 3.33333333e-01],
       [4.28571429e-01, 3.50000000e+00, 2.85714286e-01, 5.29411765e-01,
        3.03030303e-01, 3.66666667e-01],
       [7.05882353e-01, 5.41666667e-01, 3.50000000e+00, 1.50000000e+01,
        1.45454545e+00, 5.31250000e-01],
       [5.14285714e-01, 6.33333333e-01, 8.33333333e-01, 4.20000000e+00,
        1.22222222e+00, 3.83333333e+00],
       [3.42857143e+00, 1.00000000e+00, 6.50000000e+00, 1.35000000e+00,
        1.40000000e+00, 1.11538462e+00],
       [1.20000000e+00, 1.47619048e+00, 4.57142857e+00, 5.50000000e+00,
        1.21428571e+00, 3.50000000e+01]])

# Boolaen indexing

In [119]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [120]:
bool_arr = [False, True, True, False, True, False, True, True, True,False]

In [121]:
arr[bool_arr]

array([2, 3, 5, 7, 8, 9])

In [124]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [128]:
arr[arr%2==0]

array([ 2,  4,  6,  8, 10])

In [129]:
arr[(arr>4) & (arr<10)]

array([5, 6, 7, 8, 9])

In [130]:
arr[(arr>4) | (arr<10)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [131]:
arr2

array([[12, 30, 16, 28, 33, 15],
       [14,  2, 28, 17, 33, 30],
       [17, 24,  4,  1, 11, 32],
       [35, 30, 24,  5, 18,  6],
       [ 7, 25,  4, 20, 20, 26],
       [25, 21,  7,  6, 28,  1]])

In [133]:
np.where(arr2>12,30,arr2)

array([[12, 30, 30, 30, 30, 30],
       [30,  2, 30, 30, 30, 30],
       [30, 30,  4,  1, 11, 30],
       [30, 30, 30,  5, 30,  6],
       [ 7, 30,  4, 30, 30, 30],
       [30, 30,  7,  6, 30,  1]])

In [135]:
np.where(arr2>=12,1,arr2)

array([[ 1,  1,  1,  1,  1,  1],
       [ 1,  2,  1,  1,  1,  1],
       [ 1,  1,  4,  1, 11,  1],
       [ 1,  1,  1,  5,  1,  6],
       [ 7,  1,  4,  1,  1,  1],
       [ 1,  1,  7,  6,  1,  1]])

# concatnating array

In [137]:
new_arr=np.concatenate([arr2,arr2d])

In [138]:
new_arr

array([[12, 30, 16, 28, 33, 15],
       [14,  2, 28, 17, 33, 30],
       [17, 24,  4,  1, 11, 32],
       [35, 30, 24,  5, 18,  6],
       [ 7, 25,  4, 20, 20, 26],
       [25, 21,  7,  6, 28,  1],
       [ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [141]:
new_arr=np.concatenate([arr2,arr2d],axis=1)

In [142]:
new_arr

array([[12, 30, 16, 28, 33, 15,  0,  1,  2,  3,  4,  5],
       [14,  2, 28, 17, 33, 30,  6,  7,  8,  9, 10, 11],
       [17, 24,  4,  1, 11, 32, 12, 13, 14, 15, 16, 17],
       [35, 30, 24,  5, 18,  6, 18, 19, 20, 21, 22, 23],
       [ 7, 25,  4, 20, 20, 26, 24, 25, 26, 27, 28, 29],
       [25, 21,  7,  6, 28,  1, 30, 31, 32, 33, 34, 35]])

In [143]:
new_arr=np.concatenate([arr2,arr2d],axis=0)

In [145]:
new_arr

array([[12, 30, 16, 28, 33, 15],
       [14,  2, 28, 17, 33, 30],
       [17, 24,  4,  1, 11, 32],
       [35, 30, 24,  5, 18,  6],
       [ 7, 25,  4, 20, 20, 26],
       [25, 21,  7,  6, 28,  1],
       [ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

# spliting of Array

In [149]:
np.split(new_arr,6,axis=0)

[array([[12, 30, 16, 28, 33, 15],
        [14,  2, 28, 17, 33, 30]]),
 array([[17, 24,  4,  1, 11, 32],
        [35, 30, 24,  5, 18,  6]]),
 array([[ 7, 25,  4, 20, 20, 26],
        [25, 21,  7,  6, 28,  1]]),
 array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [152]:
np.split(new_arr,[10,2],axis=0)

[array([[12, 30, 16, 28, 33, 15],
        [14,  2, 28, 17, 33, 30],
        [17, 24,  4,  1, 11, 32],
        [35, 30, 24,  5, 18,  6],
        [ 7, 25,  4, 20, 20, 26],
        [25, 21,  7,  6, 28,  1],
        [ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([], shape=(0, 6), dtype=int32),
 array([[17, 24,  4,  1, 11, 32],
        [35, 30, 24,  5, 18,  6],
        [ 7, 25,  4, 20, 20, 26],
        [25, 21,  7,  6, 28,  1],
        [ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]